// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abbreviations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmAbbreviation = `-- name: ConfirmAbbreviation :one
UPDATE abbreviations SET source = 'USER_ADDED' WHERE id = $1
RETURNING id, user_id, token, exercise_id, modifier_type, modifier_value, source, created_at
`

func (q *Queries) ConfirmAbbreviation(ctx context.Context, id string) (Abbreviation, error) {
	row := q.db.QueryRow(ctx, confirmAbbreviation, id)
	var i Abbreviation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExerciseID,
		&i.ModifierType,
		&i.ModifierValue,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createAbbreviation = `-- name: CreateAbbreviation :one
INSERT INTO abbreviations (id, user_id, token, exercise_id, modifier_type, modifier_value, source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token, exercise_id, modifier_type, modifier_value, source, created_at
`

type CreateAbbreviationParams struct {
	ID            string      `db:"id" json:"id"`
	UserID        string      `db:"user_id" json:"user_id"`
	Token         string      `db:"token" json:"token"`
	ExerciseID    pgtype.Text `db:"exercise_id" json:"exercise_id"`
	ModifierType  pgtype.Text `db:"modifier_type" json:"modifier_type"`
	ModifierValue pgtype.Text `db:"modifier_value" json:"modifier_value"`
	Source        string      `db:"source" json:"source"`
}

func (q *Queries) CreateAbbreviation(ctx context.Context, arg CreateAbbreviationParams) (Abbreviation, error) {
	row := q.db.QueryRow(ctx, createAbbreviation,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExerciseID,
		arg.ModifierType,
		arg.ModifierValue,
		arg.Source,
	)
	var i Abbreviation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExerciseID,
		&i.ModifierType,
		&i.ModifierValue,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const findAbbreviationsForTokens = `-- name: FindAbbreviationsForTokens :many
SELECT id, user_id, token, exercise_id, modifier_type, modifier_value, source, created_at FROM abbreviations WHERE user_id = $1 AND token = ANY($2::text[])
`

type FindAbbreviationsForTokensParams struct {
	UserID string   `db:"user_id" json:"user_id"`
	Tokens []string `db:"tokens" json:"tokens"`
}

func (q *Queries) FindAbbreviationsForTokens(ctx context.Context, arg FindAbbreviationsForTokensParams) ([]Abbreviation, error) {
	rows, err := q.db.Query(ctx, findAbbreviationsForTokens, arg.UserID, arg.Tokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Abbreviation{}
	for rows.Next() {
		var i Abbreviation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.ExerciseID,
			&i.ModifierType,
			&i.ModifierValue,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAbbreviationByUserAndToken = `-- name: GetAbbreviationByUserAndToken :one
SELECT id, user_id, token, exercise_id, modifier_type, modifier_value, source, created_at FROM abbreviations WHERE user_id = $1 AND token = $2
`

type GetAbbreviationByUserAndTokenParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Token  string `db:"token" json:"token"`
}

func (q *Queries) GetAbbreviationByUserAndToken(ctx context.Context, arg GetAbbreviationByUserAndTokenParams) (Abbreviation, error) {
	row := q.db.QueryRow(ctx, getAbbreviationByUserAndToken, arg.UserID, arg.Token)
	var i Abbreviation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExerciseID,
		&i.ModifierType,
		&i.ModifierValue,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listAbbreviationsForUser = `-- name: ListAbbreviationsForUser :many
SELECT id, user_id, token, exercise_id, modifier_type, modifier_value, source, created_at FROM abbreviations WHERE user_id = $1 ORDER BY token
`

func (q *Queries) ListAbbreviationsForUser(ctx context.Context, userID string) ([]Abbreviation, error) {
	rows, err := q.db.Query(ctx, listAbbreviationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Abbreviation{}
	for rows.Next() {
		var i Abbreviation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.ExerciseID,
			&i.ModifierType,
			&i.ModifierValue,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
