// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (id, name, category)
VALUES ($1, $2, $3)
RETURNING id, name, category, created_at
`

type CreateExerciseParams struct {
	ID       string `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	Category string `db:"category" json:"category"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.ID, arg.Name, arg.Category)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const createMuscleMapEntry = `-- name: CreateMuscleMapEntry :exec
INSERT INTO muscle_map_entries (id, exercise_id, muscle, role, weight)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMuscleMapEntryParams struct {
	ID         string  `db:"id" json:"id"`
	ExerciseID string  `db:"exercise_id" json:"exercise_id"`
	Muscle     string  `db:"muscle" json:"muscle"`
	Role       string  `db:"role" json:"role"`
	Weight     float32 `db:"weight" json:"weight"`
}

func (q *Queries) CreateMuscleMapEntry(ctx context.Context, arg CreateMuscleMapEntryParams) error {
	_, err := q.db.Exec(ctx, createMuscleMapEntry,
		arg.ID,
		arg.ExerciseID,
		arg.Muscle,
		arg.Role,
		arg.Weight,
	)
	return err
}

const findExistingExerciseIDs = `-- name: FindExistingExerciseIDs :many
SELECT id FROM exercises WHERE id = ANY($1::text[])
`

func (q *Queries) FindExistingExerciseIDs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, findExistingExerciseIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseByName = `-- name: GetExerciseByName :one
SELECT id, name, category, created_at FROM exercises WHERE name = $1
`

func (q *Queries) GetExerciseByName(ctx context.Context, name string) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByName, name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getMuscleMapForExercise = `-- name: GetMuscleMapForExercise :many
SELECT id, exercise_id, muscle, role, weight FROM muscle_map_entries WHERE exercise_id = $1
`

func (q *Queries) GetMuscleMapForExercise(ctx context.Context, exerciseID string) ([]MuscleMapEntry, error) {
	rows, err := q.db.Query(ctx, getMuscleMapForExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MuscleMapEntry{}
	for rows.Next() {
		var i MuscleMapEntry
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.Muscle,
			&i.Role,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
