// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: goals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, user_id, type, description, is_active)
VALUES ($1, $2, $3, $4, TRUE)
RETURNING id, user_id, type, description, is_active, created_at
`

type CreateGoalParams struct {
	ID          string  `db:"id" json:"id"`
	UserID      string  `db:"user_id" json:"user_id"`
	Type        string  `db:"type" json:"type"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Description,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createGoalTarget = `-- name: CreateGoalTarget :exec
INSERT INTO goal_targets (id, goal_id, muscle, min_sets_per_week, max_sets_per_week)
VALUES ($1, $2, $3, $4, $5)
`

type CreateGoalTargetParams struct {
	ID             string `db:"id" json:"id"`
	GoalID         string `db:"goal_id" json:"goal_id"`
	Muscle         string `db:"muscle" json:"muscle"`
	MinSetsPerWeek int32  `db:"min_sets_per_week" json:"min_sets_per_week"`
	MaxSetsPerWeek int32  `db:"max_sets_per_week" json:"max_sets_per_week"`
}

func (q *Queries) CreateGoalTarget(ctx context.Context, arg CreateGoalTargetParams) error {
	_, err := q.db.Exec(ctx, createGoalTarget,
		arg.ID,
		arg.GoalID,
		arg.Muscle,
		arg.MinSetsPerWeek,
		arg.MaxSetsPerWeek,
	)
	return err
}

const deactivateGoalsForUser = `-- name: DeactivateGoalsForUser :exec
UPDATE goals SET is_active = FALSE WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) DeactivateGoalsForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deactivateGoalsForUser, userID)
	return err
}

const getActiveGoalForUser = `-- name: GetActiveGoalForUser :one
SELECT id, user_id, type, description, is_active, created_at FROM goals WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) GetActiveGoalForUser(ctx context.Context, userID string) (Goal, error) {
	row := q.db.QueryRow(ctx, getActiveGoalForUser, userID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getGoalTargetsForGoal = `-- name: GetGoalTargetsForGoal :many
SELECT id, goal_id, muscle, min_sets_per_week, max_sets_per_week FROM goal_targets WHERE goal_id = $1
`

func (q *Queries) GetGoalTargetsForGoal(ctx context.Context, goalID string) ([]GoalTarget, error) {
	rows, err := q.db.Query(ctx, getGoalTargetsForGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoalTarget{}
	for rows.Next() {
		var i GoalTarget
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Muscle,
			&i.MinSetsPerWeek,
			&i.MaxSetsPerWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsWithEntriesInWeek = `-- name: GetSessionsWithEntriesInWeek :many
SELECT
  set_entries.exercise_id,
  set_entries.sets,
  muscle_map_entries.muscle
FROM workout_sessions
JOIN set_entries ON set_entries.session_id = workout_sessions.id
JOIN muscle_map_entries ON muscle_map_entries.exercise_id = set_entries.exercise_id
WHERE workout_sessions.user_id = $1
  AND workout_sessions.date >= $2
  AND workout_sessions.date < $3
  AND set_entries.sets IS NOT NULL
`

type GetSessionsWithEntriesInWeekParams struct {
	UserID string      `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

type GetSessionsWithEntriesInWeekRow struct {
	ExerciseID *string `db:"exercise_id" json:"exercise_id"`
	Sets       *int32  `db:"sets" json:"sets"`
	Muscle     string  `db:"muscle" json:"muscle"`
}

func (q *Queries) GetSessionsWithEntriesInWeek(ctx context.Context, arg GetSessionsWithEntriesInWeekParams) ([]GetSessionsWithEntriesInWeekRow, error) {
	rows, err := q.db.Query(ctx, getSessionsWithEntriesInWeek, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionsWithEntriesInWeekRow{}
	for rows.Next() {
		var i GetSessionsWithEntriesInWeekRow
		if err := rows.Scan(&i.ExerciseID, &i.Sets, &i.Muscle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
