// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: magic_link_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMagicLinkToken = `-- name: ConsumeMagicLinkToken :one
UPDATE magic_link_tokens
   SET used_at = NOW()
 WHERE token_hash = $1
   AND used_at IS NULL
   AND expires_at > NOW()
   AND token_type = 'magic_link'
RETURNING id, email, expires_at
`

type ConsumeMagicLinkTokenRow struct {
	ID        string             `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ConsumeMagicLinkToken(ctx context.Context, tokenHash string) (ConsumeMagicLinkTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeMagicLinkToken, tokenHash)
	var i ConsumeMagicLinkTokenRow
	err := row.Scan(&i.ID, &i.Email, &i.ExpiresAt)
	return i, err
}

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one
INSERT INTO magic_link_tokens (id, token_hash, token_type, user_id, email, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, token_hash, token_type, user_id, email, expires_at, used_at, created_at
`

type CreateMagicLinkTokenParams struct {
	ID        string             `db:"id" json:"id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	TokenType string             `db:"token_type" json:"token_type"`
	UserID    pgtype.Text        `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, createMagicLinkToken,
		arg.ID,
		arg.TokenHash,
		arg.TokenType,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
	)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenType,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM magic_link_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getMagicLinkTokenByHash = `-- name: GetMagicLinkTokenByHash :one
SELECT id, token_hash, token_type, user_id, email, expires_at, used_at, created_at FROM magic_link_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
  AND token_type = 'magic_link'
`

func (q *Queries) GetMagicLinkTokenByHash(ctx context.Context, tokenHash string) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, getMagicLinkTokenByHash, tokenHash)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenType,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicLinkTokenUsed = `-- name: MarkMagicLinkTokenUsed :exec
UPDATE magic_link_tokens SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkMagicLinkTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markMagicLinkTokenUsed, id)
	return err
}
