// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Abbreviation struct {
	ID            string             `db:"id" json:"id"`
	UserID        string             `db:"user_id" json:"user_id"`
	Token         string             `db:"token" json:"token"`
	ExerciseID    pgtype.Text        `db:"exercise_id" json:"exercise_id"`
	ModifierType  pgtype.Text        `db:"modifier_type" json:"modifier_type"`
	ModifierValue pgtype.Text        `db:"modifier_value" json:"modifier_value"`
	Source        string             `db:"source" json:"source"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Exercise struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Category  string             `db:"category" json:"category"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Goal struct {
	ID          string             `db:"id" json:"id"`
	UserID      string             `db:"user_id" json:"user_id"`
	Type        string             `db:"type" json:"type"`
	Description pgtype.Text        `db:"description" json:"description"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GoalTarget struct {
	ID             string `db:"id" json:"id"`
	GoalID         string `db:"goal_id" json:"goal_id"`
	Muscle         string `db:"muscle" json:"muscle"`
	MinSetsPerWeek int32  `db:"min_sets_per_week" json:"min_sets_per_week"`
	MaxSetsPerWeek int32  `db:"max_sets_per_week" json:"max_sets_per_week"`
}

type MagicLinkToken struct {
	ID        string             `db:"id" json:"id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	TokenType string             `db:"token_type" json:"token_type"`
	UserID    pgtype.Text        `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MuscleMapEntry struct {
	ID         string  `db:"id" json:"id"`
	ExerciseID string  `db:"exercise_id" json:"exercise_id"`
	Muscle     string  `db:"muscle" json:"muscle"`
	Role       string  `db:"role" json:"role"`
	Weight     float32 `db:"weight" json:"weight"`
}

type RiverClient struct {
	ID        string             `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Metadata  json.RawMessage    `db:"metadata" json:"metadata"`
	PausedAt  pgtype.Timestamptz `db:"paused_at" json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string             `db:"river_client_id" json:"river_client_id"`
	Name             string             `db:"name" json:"name"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MaxWorkers       int64              `db:"max_workers" json:"max_workers"`
	Metadata         json.RawMessage    `db:"metadata" json:"metadata"`
	NumJobsCompleted int64              `db:"num_jobs_completed" json:"num_jobs_completed"`
	NumJobsRunning   int64              `db:"num_jobs_running" json:"num_jobs_running"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RiverJob struct {
	ID           int64              `db:"id" json:"id"`
	State        RiverJobState      `db:"state" json:"state"`
	Attempt      int16              `db:"attempt" json:"attempt"`
	MaxAttempts  int16              `db:"max_attempts" json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `db:"finalized_at" json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	Priority     int16              `db:"priority" json:"priority"`
	Args         json.RawMessage    `db:"args" json:"args"`
	AttemptedBy  []string           `db:"attempted_by" json:"attempted_by"`
	Errors       []json.RawMessage  `db:"errors" json:"errors"`
	Kind         string             `db:"kind" json:"kind"`
	Metadata     json.RawMessage    `db:"metadata" json:"metadata"`
	Queue        string             `db:"queue" json:"queue"`
	Tags         []string           `db:"tags" json:"tags"`
	UniqueKey    []byte             `db:"unique_key" json:"unique_key"`
	UniqueStates pgtype.Bits        `db:"unique_states" json:"unique_states"`
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz `db:"elected_at" json:"elected_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LeaderID  string             `db:"leader_id" json:"leader_id"`
	Name      string             `db:"name" json:"name"`
}

type RiverMigration struct {
	ID        int64              `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Version   int64              `db:"version" json:"version"`
}

type RiverQueue struct {
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Metadata  json.RawMessage    `db:"metadata" json:"metadata"`
	PausedAt  pgtype.Timestamptz `db:"paused_at" json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SetEntry struct {
	ID         string             `db:"id" json:"id"`
	SessionID  string             `db:"session_id" json:"session_id"`
	ExerciseID pgtype.Text        `db:"exercise_id" json:"exercise_id"`
	Equipment  pgtype.Text        `db:"equipment" json:"equipment"`
	WeightKg   pgtype.Float4      `db:"weight_kg" json:"weight_kg"`
	Reps       pgtype.Int4        `db:"reps" json:"reps"`
	Sets       pgtype.Int4        `db:"sets" json:"sets"`
	RawText    string             `db:"raw_text" json:"raw_text"`
	ParsedBy   string             `db:"parsed_by" json:"parsed_by"`
	EntryOrder int32              `db:"entry_order" json:"entry_order"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID              string             `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	AvatarObjectKey pgtype.Text        `db:"avatar_object_key" json:"avatar_object_key"`
	AvatarUpdatedAt pgtype.Timestamptz `db:"avatar_updated_at" json:"avatar_updated_at"`
	Phone           pgtype.Text        `db:"phone" json:"phone"`
	Locale          string             `db:"locale" json:"locale"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WorkoutSession struct {
	ID        string             `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Date      pgtype.Date        `db:"date" json:"date"`
	Notes     pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
