// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSetEntry = `-- name: CreateSetEntry :exec
INSERT INTO set_entries (id, session_id, exercise_id, equipment, weight_kg, reps, sets, raw_text, parsed_by, entry_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateSetEntryParams struct {
	ID         string   `db:"id" json:"id"`
	SessionID  string   `db:"session_id" json:"session_id"`
	ExerciseID *string  `db:"exercise_id" json:"exercise_id"`
	Equipment  *string  `db:"equipment" json:"equipment"`
	WeightKg   *float32 `db:"weight_kg" json:"weight_kg"`
	Reps       *int32   `db:"reps" json:"reps"`
	Sets       *int32   `db:"sets" json:"sets"`
	RawText    string   `db:"raw_text" json:"raw_text"`
	ParsedBy   string   `db:"parsed_by" json:"parsed_by"`
	EntryOrder int32    `db:"entry_order" json:"entry_order"`
}

func (q *Queries) CreateSetEntry(ctx context.Context, arg CreateSetEntryParams) error {
	_, err := q.db.Exec(ctx, createSetEntry,
		arg.ID,
		arg.SessionID,
		arg.ExerciseID,
		arg.Equipment,
		arg.WeightKg,
		arg.Reps,
		arg.Sets,
		arg.RawText,
		arg.ParsedBy,
		arg.EntryOrder,
	)
	return err
}

const deleteSetEntriesForSession = `-- name: DeleteSetEntriesForSession :exec
DELETE FROM set_entries WHERE session_id = $1
`

func (q *Queries) DeleteSetEntriesForSession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSetEntriesForSession, sessionID)
	return err
}

const getSetEntriesForSession = `-- name: GetSetEntriesForSession :many
SELECT id, session_id, exercise_id, equipment, weight_kg, reps, sets, raw_text, parsed_by, entry_order, created_at FROM set_entries WHERE session_id = $1 ORDER BY entry_order
`

func (q *Queries) GetSetEntriesForSession(ctx context.Context, sessionID string) ([]SetEntry, error) {
	rows, err := q.db.Query(ctx, getSetEntriesForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetEntry{}
	for rows.Next() {
		var i SetEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.Equipment,
			&i.WeightKg,
			&i.Reps,
			&i.Sets,
			&i.RawText,
			&i.ParsedBy,
			&i.EntryOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetEntriesForSessionsInRange = `-- name: ListSetEntriesForSessionsInRange :many
SELECT set_entries.id, set_entries.session_id, set_entries.exercise_id, set_entries.equipment, set_entries.weight_kg, set_entries.reps, set_entries.sets, set_entries.raw_text, set_entries.parsed_by, set_entries.entry_order, set_entries.created_at FROM set_entries
JOIN workout_sessions ON workout_sessions.id = set_entries.session_id
WHERE workout_sessions.user_id = $1 AND workout_sessions.date >= $2 AND workout_sessions.date <= $3
ORDER BY workout_sessions.date ASC, set_entries.entry_order ASC
`

type ListSetEntriesForSessionsInRangeParams struct {
	UserID string      `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListSetEntriesForSessionsInRange(ctx context.Context, arg ListSetEntriesForSessionsInRangeParams) ([]SetEntry, error) {
	rows, err := q.db.Query(ctx, listSetEntriesForSessionsInRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetEntry{}
	for rows.Next() {
		var i SetEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.Equipment,
			&i.WeightKg,
			&i.Reps,
			&i.Sets,
			&i.RawText,
			&i.ParsedBy,
			&i.EntryOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSessionsInRange = `-- name: ListWorkoutSessionsInRange :many
SELECT id, user_id, date, notes, created_at FROM workout_sessions WHERE user_id = $1 AND date >= $2 AND date <= $3 ORDER BY date ASC
`

type ListWorkoutSessionsInRangeParams struct {
	UserID string      `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListWorkoutSessionsInRange(ctx context.Context, arg ListWorkoutSessionsInRangeParams) ([]WorkoutSession, error) {
	rows, err := q.db.Query(ctx, listWorkoutSessionsInRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSession{}
	for rows.Next() {
		var i WorkoutSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkoutSession = `-- name: UpsertWorkoutSession :one
INSERT INTO workout_sessions (id, user_id, date, notes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, date) DO UPDATE SET notes = EXCLUDED.notes
RETURNING id, user_id, date, notes, created_at
`

type UpsertWorkoutSessionParams struct {
	ID     string      `db:"id" json:"id"`
	UserID string      `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Notes  *string     `db:"notes" json:"notes"`
}

func (q *Queries) UpsertWorkoutSession(ctx context.Context, arg UpsertWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, upsertWorkoutSession,
		arg.ID,
		arg.UserID,
		arg.Date,
		arg.Notes,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
